CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE clients (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('UTC', now()),  
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('UTC', now()),
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  dob DATE,
  mobile VARCHAR(20),
  email VARCHAR(100) UNIQUE,
  custom_fields JSONB DEFAULT '{}'
);

CREATE TABLE medical_history (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id INTEGER REFERENCES clients(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('UTC', now()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('UTC', now()),
  custom_fields JSONB DEFAULT '{}'
);

CREATE TABLE tcm (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id INTEGER REFERENCES clients(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('UTC', now()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('UTC', now()),
  custom_fields JSONB DEFAULT '{}'
);

CREATE TABLE treatments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id INTEGER REFERENCES clients(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('UTC', now()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('UTC', now()),
  date DATE NOT NULL,
  duration_minutes INTEGER,
  notes TEXT,
  custom_fields JSONB DEFAULT '{}'
);

CREATE TABLE appointments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id INTEGER REFERENCES clients(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('UTC', now()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('UTC', now()),
  start_time TIMESTAMP WITH TIME ZONE NOT NULL,
  end_time TIMESTAMP WITH TIME ZONE NOT NULL,
  appointment_type VARCHAR(50),
  notes TEXT,
  custom_fields JSONB DEFAULT '{}'
);

CREATE TABLE forms (
  id VARCHAR(50) PRIMARY KEY,
  custom_fields JSONB DEFAULT '{}'
);

CREATE TABLE categories (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(50),
  color VARCHAR(50)
);